### ISSUE TITLE
How to build for android app?

### ISSUE THREAD

**Issue by huutho-dev** [yangjian1218/face_landmark#1]

**Comment by yangjian1218** [comment]
make project with android studio, and modify MakeLists.txt  add: add_library(facelandncnn SHARED ${DIR_SRCS})
modify main cpp file with JNI to connect java class

**Comment by huutho-dev** [comment]
Thanks for reply.
Can you provide more detailed documentation or code?  I am newbie.

**Comment by yangjian1218** [comment]
@huutho-dev sorry,I cant share the detail , you can learn from Tencent:NCNN there are same samples . 
https://github.com/Tencent/ncnn

**Comment by huutho-dev** [comment]
Ok, thank for your suggestion!
